steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --platform
      - linux/amd64
      - -f
      - Dockerfile
      - -t
      - ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${_TAG}
      - .
images:
  - ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${_TAG}
substitutions:
  _LOCATION: us-central1
  _REPO: agent-sandbox
  _IMAGE: claude-agent-sandbox
  _TAG: v7
